### ISSUE TITLE
multi-node inference

### ISSUE THREAD

**Issue by lzy37ld** [mexiQQ/llama-70b-chat-4-shards#1]
Hi MexiQQ(十四), Thanks for this great implementation!
But it still could not resolve my concern as though it's 4 shards now, my VRAM for one node(4 gpus)could not handle 70B and I probably need multi-node inference.

DO you have any suggestions or scripts about doing multi-node inference?

**Comment by lzy37ld** [comment]
I am From this [page](https://github.com/facebookresearch/llama/issues/594#issuecomment-1783497779)

**Comment by mexiQQ** [comment]
Hi, it only supports inference on a single node with multiple (2/4/6/8) GPUs.
